name: CI - MLflow Project Training & Docker Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: '3.12'
        environment-file: MLProject/conda.yaml
        activate-environment: wine_ml_env
        auto-activate-base: false
        miniforge-variant: Mambaforge

    - name: Run MLflow Project
      shell: bash -l {0}
      run: |
        cd MLProject
        mlflow run .   # Ini yang diminta reviewer

    - name: Upload MLflow artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mlruns
        path: MLProject/mlruns/

    # Advance: Commit artifacts back
    - name: Commit artifacts to repo
      shell: bash -l {0}
      run: |
        cd MLProject
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add mlruns/
        git diff --staged --quiet || git commit -m "Update MLflow artifacts from CI [skip ci]"
        git push || echo "No changes"
