name: CI - Retrain Model

permissions:
  contents: write
  actions: read

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow scikit-learn pandas imbalanced-learn

    - name: Run training
      run: |
        cd MLProject
        python modelling.py

    - name: Upload MLflow artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mlruns
        path: MLProject/mlruns/
        if-no-files-found: warn

    - name: Commit and push MLflow artifacts to repo
      run: |
        cd MLProject
        git config --global user.name "IKadekFredlySukrata"
        git config --global user.email "fredlysukrata@gmail.com"
        
        git add mlruns/
        
        git diff --quiet && git diff --staged --quiet || git commit -m "Update MLflow artifacts from CI run"
        
        git push origin main
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Get latest run ID
      id: get_run
      run: |
        cd MLProject
        python - <<EOF
        import mlflow
        client = mlflow.MlflowClient()
        exp = client.get_experiment_by_name("Wine_Classification_Experiment")
        runs = client.search_runs(exp.experiment_id, max_results=1, order_by=["start_time DESC"])
        run_id = runs[0].info.run_id
        print(run_id)
        with open("$GITHUB_OUTPUT", "a") as f:
          f.write(f"run_id={run_id}\n")
        EOF

    - name: Build and push Docker image
      run: |
        cd MLProject
        mlflow models build-docker -m "runs:/${{ steps.get_run.outputs.run_id }}/model" -n "wine-model-server" --enable-mlserver
        docker tag wine-model-server ${{ secrets.DOCKERHUB_USERNAME }}/wine-model-server:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/wine-model-server:latest
